### ISSUE TITLE
failed with exit code Some(101):

### ISSUE THREAD

**Issue by PatrickAlphaC** [matter-labs/era-compiler-vyper#119] opened 2024-10-24 00:49 UTC
### 🐛 Bug Report

Something is breaking, and I'm not sure what. I've made a minimal repo to demonstrate it. 

Running: 

```bash
vyper basic_token.vy
```

Works fine, but running:

```
zkvyper basic_token.vy
```

Fails with:

```
Contract `basic_token.vy`: "/usr/local/bin/zkvyper" subprocess compiling `basic_token.vy` failed with exit code Some(101):

thread 'main' panicked at /Users/hetzner/.cargo/git/checkouts/era-compiler-llvm-context-0bf7b3643ca7a776/23bd5c5/src/eravm/context/function/mod.rs:135:14:
Always exists
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It's a bit of a cryptic `Some(101)` error. 

Another thing that's odd is it's telling me the code is having an issue at the `hetzner` path. 

#### 🔄 Reproduction Steps

1. Install [uv](https://docs.astral.sh/uv/getting-started/installation/#standalone-installer)
```
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Then, clone the repo, install dependencies (snekmate)

```bash
git clone https://github.com/PatrickAlphaC/test_compile
cd test_compile
uv venv 
source .venv/bin/activate
uv sync
```

Test vyper passes
```bash
vyper basic_token.vy
```

Test zkvyper fails
```bash
vyper basic_token.vy
```

#### 🤔 Expected Behavior

I expected them to both compile

#### 🖥️ Environment

- `macos 15.0.1` M3 apple silicon 
- uv 0.4.13 (b8f9ee3b4 2024-09-19)
- Python 3.11.6
- vyper 0.4.0+commit.e9db8d9
- Vyper compiler for ZKsync v1.5.6 (LLVM build 801623bd56fbf4e1faf964d4c8dbce563bed9384)

#### Full error:

Command:
```bash
RUST_BACKTRACE=full zkvyper basic_token.vy
```

Error:
```
Contract `basic_token.vy`: "/usr/local/bin/zkvyper" subprocess compiling `basic_token.vy` failed with exit code Some(101):

thread 'main' panicked at /Users/hetzner/.cargo/git/checkouts/era-compiler-llvm-context-0bf7b3643ca7a776/23bd5c5/src/eravm/context/function/mod.rs:135:14:
Always exists
stack backtrace:
   0:        0x1060a8874 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   1:        0x1060c5510 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   2:        0x1060a5800 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   3:        0x1060a86cc - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   4:        0x1060a98a4 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   5:        0x1060a9570 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   6:        0x1060aa150 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   7:        0x1060a9b8c - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   8:        0x1060a8cf8 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
   9:        0x1060a98fc - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
  10:        0x1060d9cd0 - __ZN4llvm14RegionInfoBaseINS_12RegionTraitsINS_8FunctionEEEED0Ev
  11:        0x1060d9ca4 - __ZN4llvm14RegionInfoBaseINS_12RegionTraitsINS_8FunctionEEEED0Ev
  12:        0x104745e70 - __mh_execute_header
  13:        0x1046dcd7c - __mh_execute_header
  14:        0x104661464 - __mh_execute_header
  15:        0x10469b590 - __mh_execute_header
  16:        0x1046e72e4 - __mh_execute_header
  17:        0x1046d2174 - __mh_execute_header
  18:        0x10472c280 - __mh_execute_header
  19:        0x104734000 - __mh_execute_header
  20:        0x104684d40 - __mh_execute_header
  21:        0x10464becc - __mh_execute_header
  22:        0x104647d04 - __mh_execute_header
  23:        0x10464a578 - __mh_execute_header
  24:        0x10609f078 - __ZN3lld3elf11writeResultIN4llvm6object7ELFTypeILNS2_7support10endiannessE0ELb1EEEEEvv
  25:        0x10464cb74 - __mh_execute_header
```

**Comment by hedgar2017** [comment] 2024-10-24 03:07
@PatrickAlphaC thank you! It looks interesting.

**Comment by hedgar2017** [comment] 2024-10-24 07:15
@PatrickAlphaC I tried to reproduce, but even after installing the deps got an error about missing deps with *vyper*:
```
hedgarmac@MacBook-Pro-Oleksandr test_compile % curl -LsSf https://astral.sh/uv/install.sh | sh
downloading uv 0.4.26 aarch64-apple-darwin
installing to /Users/hedgarmac/.cargo/bin
  uv
  uvx
everything's installed!
hedgarmac@MacBook-Pro-Oleksandr test_compile % uv venv 
Using CPython 3.11.10 interpreter at: /opt/homebrew/opt/python@3.11/bin/python3.11
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
hedgarmac@MacBook-Pro-Oleksandr test_compile % source .venv/bin/activate
(test_compile) hedgarmac@MacBook-Pro-Oleksandr test_compile % uv sync
Resolved 11 packages in 1ms
Prepared 10 packages in 594ms
Installed 10 packages in 18ms
 + asttokens==2.4.1
 + cbor2==5.6.5
 + importlib-metadata==8.5.0
 + packaging==23.2
 + pycryptodome==3.21.0
 + six==1.16.0
 + snekmate==0.1.0
 + vyper==0.4.0
 + wheel==0.44.0
 + zipp==3.20.2
(test_compile) hedgarmac@MacBook-Pro-Oleksandr test_compile % $TESTER_HOME/vyper-bin/vyper-0.4.0 basic_token.vy
Error compiling: basic_token.vy
vyper.exceptions.ModuleNotFound: snekmate.auth.ownable

  contract "basic_token.vy:4", line 4:0 
       3 """
  ---> 4 from snekmate.auth import ownable as ow
  -------^
       5 from snekmate.tokens import erc20

[17643] Failed to execute script 'vyper_compile' due to unhandled exception!

**Comment by PatrickAlphaC** [comment] 2024-10-24 12:44
Ah! Sorry, can you do `uv add snekmate`

**Comment by hedgar2017** [comment] 2024-10-25 16:14
Originally caused by https://github.com/vyperlang/vyper/issues/4312, but fixed in https://github.com/matter-labs/era-compiler-vyper/pull/120 by using another kind of function signature analysis.

**Closed** 2024-10-25 16:13 UTC
Labels: bug
